name: perpustakaan
description: Aplikasi Peminjaman Buku Perpustakaan UPGRIS
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo_upgris.png
